#define ZCL_CLUSTER_DOCLAB_SENSOR_CONTROL    0xFD64

#define ZCL_ATTRID_SENSOR_CONTROL_BATTERY_VOLTAGE_RATE		0x0000
#define ZCL_ATTRID_SENSOR_CONTROL_LIGHT_SENSOR_RATE			0x0001

#define ZCL_ATTRID_SC_BATTERY_VOLTAGE_RATE					0x6400
#define ZCL_ATTRID_SC_LIGHT_SENSOR_RATE						0x6401
